<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Update video gallery' => 'Изменение видео галереи',
    'Video url' => 'Ссылка на видео',
    'Be careful in Code field. Pay attention to field hint.' => 'Будьте внимательны при заполнении поля Код. Обратите внимание на подсказку.',
    'Code' => 'Код',
    'Create video' => 'Добавить видео',
    'Create video gallery' => 'Создать галерею',
    'Created at' => 'Время создания',
    'Created at {0, date, MMMM dd, YYYY HH:mm}' => 'Время создания: {0, date, dd MMMM YYYY, HH:mm}',
    'Description' => 'Описание',
    'Don\'t change this value, if you not sure for what it is for.' => 'Не меняйте значение этого поля, если не уверены в том для чего оно предназначено.',
    'Edit' => 'Изменить',
    'Galleries' => 'Галереи',
    'Information' => 'Информация',
    'Manage video galleries' => 'Управление видео галереями',
    'Manage videos' => 'Управление видео',
    'Name' => 'Название',
    'Only latin characters, numbers and symbols (.-_) allowed. Spaces not allowed.' => 'Разрешены только латинские буквы, числа и символы (.-_). Пробелы запрещены.',
    'Save' => 'Сохранить',
    'Sort index' => 'Индекс сортировки',
    'There is no video gallery with code "{code}"' => 'Галерея с кодом "{code}" не найдена',
    'Title' => 'Название',
    'Update video' => 'Изменнение видео',
    'Updated at' => 'Время изменения',
    'Video gallery' => 'Галерея',
    'Video gallery has been created' => 'Галерея была успешно создана',
    'Video gallery has been deleted' => 'Галерея была удалена',
    'Video gallery has been updated' => 'Галерея была изменена',
    'Video has been created' => 'Видео было успешно добавлено',
    'Video has been deleted' => 'Видео было удалено',
    'Video has been updated' => 'Видео было изменено',
    'Videos' => 'Видео',
    '{0, date, MMMM dd, YYYY HH:mm}' => '{0, date, dd MMMM YYYY, HH:mm}',
];
